### PR TITLE
explore HGDP metadata

### PR DESCRIPTION
**Pull request by pdiakumis**
Just putting in a short Rmd for exploring HGDP metadata for copying over (high-coverage) CRAMs to our local bucket. Not sure if this is the right repo for stuff like this.

### CODE REVIEW

**Comment by pdiakumis** [comment]
@KatalinaBobowik I've put together a mini report for exploring that HGDP bucket with CRAMs + QC + metadata. Let's chat about selecting a few (50-100?) samples this week (I've done an initial filtration based on coverage, contamination, population label agreement).

[hgdp_exploration_2021-Mar-15.html.zip](https://github.com/populationgenomics/fewgenomes/files/6141429/hgdp_exploration_2021-Mar-15.html.zip)

**Comment by KatalinaBobowik** [comment]
Perfect! @pdiakumis this looks great. I'll do a QC report of my own and then we can get together and decide.

**Comment by pdiakumis** [comment]
@KatalinaBobowik I ended up selecting 4M/4F from each of the 7 superpopulations, giving a total of 56 samples. This includes Papuan/Melanesian samples (even though their quality wasn't as good - e.g. they weren't in the filtered subset you sent through). Attaching rendered report.

[hgdp_exploration_2021-Mar-20.html.zip](https://github.com/populationgenomics/fewgenomes/files/6174984/hgdp_exploration_2021-Mar-20.html.zip)

**Review by KatalinaBobowik — APPROVED** [review]
Looks great Peter 👍

**Comment by pdiakumis** [comment]
Thanks for your work on this @KatalinaBobowik! 
As discussed, I added a few more East Asian samples and diversified the rest of the subpops a bit. Total of 65 samples (~1Tb of CRAMs). I'll get into copying these over asap.

[hgdp_exploration_2021-Mar-22.html.zip](https://github.com/populationgenomics/fewgenomes/files/6182211/hgdp_exploration_2021-Mar-22.html.zip)

**Comment by KatalinaBobowik** [comment]
Looks great Peter. Thanks for the discussion yesterday!

**Pull request merged**
